permalink: pretty
markdown: kramdown
highlighter: rouge
liquid:
  error_mode: lax

title: site title
desc: site description
keywords: site, keywords
image: "assets/img/charlievuong.webp"

# Make relative links work - adjust as needed
baseurl: /template-portfolio

# owner
author:
  name: Charlie Vuong
  email: vuong056@charlie-vuong.com

# site data
collections:
  post: { output: true }
  project: { output: true }
